---
version: 1

formatters:
  extended:
    format: "[%(levelname)s] %(asctime)s: %(name)s - %(funcName)s - %(lineno)d - %(message)s"
    timefmt: "%Y-%m-%dT%H:%M:%S%z"

  simple:
    format: "%(asctime)s: %(message)s"
    timefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
  module_log:
    class: logging.RotatingFileHandler
    level: DEBUG
    filename: "module_logs.log"
    maxBytes: 1024
    backupCount: 2
    formatter: extended
    propagate: true

  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    propagate: true

loggers:
  transcriptomics:
    handlers: [module_log, console]

  genes:
    handlers: [module_log, console]

  inputs:
    handlers: [module_log, console]

  bootstrapping:
    handlers: [module_log, console]
