---
version: 1

formatters:
  extended:
    format: "[%(levelname)s] %(asctime)s: %(name)s - %(funcName)s - %(lineno)d - %(message)s"
    timefmt: "%Y-%m-%dT%H:%M:%S"

  simple:
    format: "%(asctime)s: %(message)s"
    timefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
  module_log:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: module_logs.log
    maxBytes: 6164480
    backupCount: 2
    formatter: extended

  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

loggers:
  transcriptomics:
    handlers: [module_log, console]

  genes:
    handlers: [module_log, console]

  inputs:
    handlers: [module_log, console]

  bootstrapping:
    handlers: [module_log, console]
