# File to configure the loggers in the execution pf the Python script to perform imaging-transcriptomics
---
version: 1  # This is the only possible schema version for the current python version

formatters:
  brief:
    format: "%(asctime)s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
  default:
    format: "%(asctime)s %(name)s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
  extended:
    format: "[%(levelname)s] %(asctime)s %(name)s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    filename: analysis.log
    formatter: extended
    propagate: false

loggers:
  dev:
    handlers: [console, file_handler]
root:
  handlers: [brief, console, file_handler]

